
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 108
#define YY_END_OF_BUFFER 109
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[455] =
    {   0,
        0,    0,  109,  107,    1,    2,    1,   56,  107,  106,
       76,   74,  107,   95,   96,   71,   69,   97,   70,  101,
       72,  105,  105,   59,  102,   55,   53,   54,   58,   99,
      106,   93,   94,   75,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
       91,   73,   92,   57,    1,   64,    0,  105,    0,  106,
       87,   68,   83,    0,    0,   82,   65,   80,   66,   81,
       60,  103,    0,  105,    0,  104,   86,  105,  105,    0,
        0,    0,    0,    0,  105,  105,    0,    0,   98,   78,
       63,   61,   62,   77,   85,  106,  106,  106,  106,  106,

      106,  106,  106,  106,  106,   15,  106,  106,  106,  106,
      106,  106,  106,  106,   24,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,   84,   67,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  100,  105,  105,    0,
        0,    0,    0,    0,  104,  104,  105,  105,    0,  105,
      105,    0,    0,    0,  105,    0,  105,    0,  105,  105,
      105,    0,    0,  105,  105,   89,   88,   79,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,   23,  106,  106,  106,

       29,  106,  106,   33,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
       49,  106,  106,  106,    0,    0,    0,    0,    0,    0,
        0,    0,  105,    0,    0,  104,  104,  104,  105,    0,
        0,  105,    0,  105,  105,    0,  105,  105,    0,    0,
        0,  105,  105,    0,    0,  105,    0,    0,  105,  105,
        0,  105,    0,   90,  106,  106,  106,  106,    7,    8,
      106,   10,  106,  106,  106,  106,  106,   17,   18,  106,
      106,  106,  106,   25,  106,  106,  106,  106,   31,  106,
      105,  106,  106,  106,  106,  106,  106,  106,  106,  106,

      106,  106,   45,  106,  106,  105,   50,  106,  106,    0,
        0,    0,    0,  105,    0,  104,  104,  105,    0,    0,
        0,    0,    0,  105,    0,  106,  106,  106,    6,    9,
       11,   12,  106,  106,  106,  106,   20,   22,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,   39,  106,
      106,   42,  106,  106,   46,  106,  106,   52,    0,    0,
        0,    0,  104,    0,  105,  105,    0,    0,  106,    4,
      106,  106,  106,   16,  106,  106,  106,   27,  106,  106,
       32,  106,  106,  106,   37,   38,   40,  106,   43,  106,
       47,  106,  106,    0,  104,    0,    0,  106,    5,  106,

       14,   19,   21,  106,  106,  106,   34,   35,  106,  106,
      106,  106,  106,    0,  104,    0,    0,    3,   13,  106,
      106,  106,  106,   41,  106,  106,   51,    0,    0,    0,
      106,  106,   30,   36,  106,   48,    0,    0,    0,   26,
       28,  106,    0,    0,    0,  106,    0,    0,    0,   44,
      105,    0,  105,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   22,   22,   22,   22,   23,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   37,   38,   37,   38,   39,   37,   37,   40,   41,
       37,   37,   38,   37,   37,   37,   37,   42,   37,   37,
       43,   44,   45,   46,   47,    1,   48,   49,   50,   51,

       52,   53,   54,   55,   56,   37,   57,   58,   59,   60,
       61,   62,   37,   63,   64,   65,   66,   67,   68,   69,
       70,   71,   72,   73,   74,   75,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[76] =
    {   0,
        1,    1,    2,    2,    1,    1,    3,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    5,    1,    6,    6,
        6,    6,    6,    1,    1,    1,    1,    1,    1,    1,
        6,    6,    6,    6,    6,    6,    3,    3,    7,    3,
        8,    3,    1,    1,    1,    1,    8,    6,    6,    6,
        6,    6,    6,    3,    3,    3,    3,    7,    3,    3,
        3,    8,    3,    3,    3,    9,    3,    3,    3,    3,
        3,    1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[473] =
    {   0,
        0,    0, 1018, 1181,   74, 1181,   75,  990,   74,    0,
      989,   72,  971, 1181, 1181,  987,   68, 1181,   69,   70,
       85,  102,  155,  989, 1181,   74,  985,   77, 1181, 1181,
        0, 1181, 1181,  978,   45,   45,   59,   50,   69,   84,
      943,   93,  942,   91,   65,  950,   93,   92,  940,  945,
     1181,   57, 1181, 1181,   84, 1181,  120, 1181,  208,    0,
     1181, 1181, 1181,  989,  269, 1181, 1181, 1181, 1181, 1181,
     1181, 1181,  975,  317,  166,  947, 1181,  164,  354,  202,
      116,  219,  973,  225,  261, 1181,  244,  273, 1181,  962,
     1181, 1181, 1181,  138, 1181,  924,  923,  925,  933,  919,

      103,  935,  934,  913,  919,  904,  905,  902,  902,  908,
      905,  903,  894,  887,    0,  889,  116,  885,  878,  874,
      883,  890,  132,  890,  873,  875,  134,  873,  878,  866,
      140,  237,  153,  869, 1181, 1181,  199,  280,  306,  206,
      858,  913,  295,  323,  106,  856, 1181,    0, 1181,  340,
      360,  274,  306,  354,  877,  129,  394, 1181,  376,  401,
     1181,  870,  435,  441,  212,  365,  447,    0,  433,  457,
        0,  486,  412,  491,  496, 1181, 1181,  882,  843,  855,
      848,  857,  852,  851,  846,  831,  829,  191,  844,  835,
      831,  823,  829,  815,  829,  828,    0,  814,  143,  809,

      810,  807,  796,    0,  793,  793,  781,  782,  788,  779,
      780,  777,  785,  788,  774,  787,  771,  773,  773,  780,
        0,  780,  766,  754,  515,  305,  767,    0,  510,  232,
        0,  526,  531,  406,  439, 1181,  334,  566,    0,  549,
      541,  586,  745,  536, 1181,  418,  604, 1181,  622,  364,
      363,  613, 1181,  642,  629,  657,  752,  663,  678, 1181,
      697,    0,  713, 1181,  738,  737,  745,  738,    0,    0,
      739,    0,  729,  727,  724,  713,  714,    0,    0,  710,
      716,  709,  701,    0,  712,  700,  714,  698,    0,  686,
        0,  703,  702,  691,  686,  667,  663,  671,  676,  661,

      673,  667,    0,  653,  649,    0,    0,  646,  656,  359,
        0,  663,    0,  718,  726,  383,  755,  762,  797,  658,
      533,  587,  736,  802,  640,  654,  630,  646,    0,    0,
        0,    0,  633,  632,  637,  637,  623,    0,  614,  607,
      607,  613,  607,  596,  583,  597,  586,  575,    0,  579,
      556,    0,  558,  549,  547,  548,  547,    0,  548,    0,
      547,    0,  837,  532,  844, 1181,  807,  533,  529,    0,
      517,  510,  508,    0,  502,  488,  505,    0,  491,  492,
        0,  487,  476,  461,    0,    0,    0,  471,    0,  462,
        0,  470,  445,  587,  879,  468,  443,  434,    0,  444,

        0,    0,    0,  433,  440,  440,    0,    0,  435,  424,
      425,  424,  421,  927,  427,  388,  405,    0,    0,  343,
      341,  339,  315,    0,  299,  283,    0,  975,  293,  290,
      277,  278,    0,    0,  259,    0, 1023,  265,  252,    0,
        0,  245, 1058,  204,  206,  185,  445,  897,  161,    0,
      195,  934,  265, 1181, 1111, 1118, 1127, 1136, 1145, 1150,
     1151, 1155, 1164,  214, 1169,  204,  186, 1172,  156,  150,
      127,  104
    } ;

static yyconst flex_int16_t yy_def[473] =
    {   0,
      454,    1,  454,  454,  454,  454,  454,  454,  455,  456,
      454,  454,  457,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      456,  454,  454,  454,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      454,  454,  454,  454,  454,  454,  455,  454,  454,  456,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  458,  459,  454,  454,  454,  454,
      454,  454,  460,  454,   23,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  456,  456,  456,  456,  456,

      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  454,  454,  455,  455,  455,  455,
      461,  454,  454,  454,  454,  462,  454,   74,  454,  454,
      454,  458,  458,  463,  459,  459,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  464,  465,   79,
       85,  454,  454,  454,   85,  454,  454,  454,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,

      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  455,  455,   59,  466,  454,  454,
      467,  454,  454,  458,  458,  454,  459,  459,  157,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  468,
      464,  465,  454,  454,  252,  454,  454,  454,  454,  454,
      454,  175,  454,  454,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,

      456,  456,  456,  456,  456,  456,  456,  456,  456,  455,
      469,  454,  470,  454,  454,  459,  459,  454,  454,  454,
      468,  468,  454,  454,  454,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,   59,  471,
      454,  472,  317,  454,  454,  454,  454,  454,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  455,  317,  454,  454,  456,  456,  456,

      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  455,  459,  454,  454,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  414,  454,  454,
      456,  456,  456,  456,  456,  456,  428,  454,  454,  456,
      456,  456,  428,  454,  454,  456,  455,  454,  454,  456,
      454,  454,  454,    0,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454
    } ;

static yyconst flex_uint16_t yy_nxt[1257] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   23,   23,   24,   25,   26,   27,   28,   29,   30,
       10,   10,   31,   10,   10,   10,   10,   31,   31,   31,
       10,   10,   32,    4,   33,   34,   10,   35,   36,   37,
       38,   39,   40,   41,   10,   42,   10,   43,   31,   44,
       31,   45,   46,   47,   48,   10,   49,   50,   10,   31,
       10,   51,   52,   53,   54,   55,   55,   55,   55,   58,
       62,   67,   72,  135,   69,   55,   73,   55,   74,   74,
       74,   74,   74,   96,   68,   70,   71,   75,   63,   90,

       91,  105,   76,   93,   94,   98,  101,   99,   97,   64,
      106,   77,  122,  102,  100,   58,  103,   59,   78,  104,
       79,   79,   79,   79,   80,   58,  107,  123,  108,  136,
      124,  110,   57,   81,  165,  165,   82,  109,  119,  111,
       58,  112,  120,   83,  113,  115,  131,  126,   84,  230,
       81,  116,  117,   82,  132,  362,  121,  127,  128,   58,
      129,  360,  130,   59,  177,  178,  184,  185,  153,  153,
       83,   78,  237,   85,   85,   85,   85,   85,  154,  200,
      201,  212,  157,  157,  157,  157,  157,  207,   86,   87,
       86,  313,  208,   58,  238,  217,  213,  158,  159,  158,

      285,   88,  218,  286,   58,   86,   87,   86,  222,  311,
      223,   58,   58,  137,  158,  159,  158,  137,   78,  250,
       80,   80,   80,   80,   80,  452,  138,  138,  138,  139,
      244,  244,  166,  161,  166,  450,   82,  167,  167,  167,
      167,  167,   59,  170,  170,  170,  170,   80,  164,  227,
      245,  140,  161,   82,  274,  275,  137,  173,  246,  173,
      137,  449,  174,  174,  174,  174,  174,  137,  448,  245,
      137,   84,  137,  141,  142,  312,  153,  153,  142,  171,
      171,  171,  171,  171,  219,   58,  154,  143,  143,  143,
      144,  175,  175,  175,  175,  175,  446,  146,  225,  225,

      225,  225,  220,  161,   58,  445,  221,  172,  153,  153,
       58,   58,  145,  229,  229,  229,  229,  142,  154,   88,
      444,  142,  161,   59,  226,  226,  226,  226,  142,  442,
      441,  142,   58,  142,  146,  148,  148,  148,  148,  148,
      440,  142,  142,  142,  142,  439,  438,  436,   59,   59,
      149,  150,  149,  232,  435,  232,  235,  235,  233,  233,
      233,  233,  233,  151,   58,  434,  154,  149,  150,  149,
       78,  236,  160,  160,  160,  160,   80,  316,  148,  148,
      148,  148,  148,  167,  167,  167,  167,  167,   82,  241,
      433,  241,  161,  162,  242,  242,  242,  242,  242,  238,

      163,  432,  359,  254,  254,   82,  151,  431,  153,  153,
      322,  161,  239,  239,  239,  239,  239,   78,  154,   80,
       80,   80,   80,   80,  254,  254,  316,  158,  159,  158,
      174,  174,  174,  174,  174,   82,  244,  244,  430,  161,
      240,  153,  153,  429,  158,  159,  158,  164,  238,  251,
       58,  154,   82,  160,  160,  160,  160,   80,  161,   80,
       80,   80,   80,   80,  246,  247,  247,  247,  247,  247,
      156,  253,  427,  254,  162,  256,  256,  256,  256,  255,
      248,  163,  248,  426,  425,  424,  423,  164,   59,  422,
      253,  421,  420,  249,  254,  419,  257,  248,  418,  248,

      417,  416,  413,  258,  171,  171,  171,  171,  171,  259,
      259,  259,  259,  259,  262,  262,  262,  262,  262,   58,
       58,  412,  411,  410,  260,  409,  260,  408,  142,  142,
      142,  142,  172,  226,  226,  226,  226,  261,  407,  406,
      405,  260,  263,  260,  233,  233,  233,  233,  233,  314,
      314,  314,  314,  314,  244,  244,  404,  403,   59,  242,
      242,  242,  242,  242,  149,  402,  149,  239,  239,  239,
      239,  239,  401,  254,  245,  400,  399,  315,  398,  322,
      397,  149,  246,  149,  317,  317,  317,  317,  317,  396,
      230,  394,   58,  245,  254,  240,  317,  317,  317,  317,

      317,  317,  393,  392,  318,  318,  318,  318,  318,  156,
      391,  390,  389,  317,  317,  317,  317,  317,  317,  158,
      388,  158,  247,  247,  247,  247,  247,  454,  387,  251,
      359,  238,  319,  322,  386,  385,  158,  248,  158,  248,
      247,  247,  247,  247,  247,  454,  384,  383,  454,  382,
      249,  253,  414,  254,  248,  323,  248,  323,  381,  255,
      324,  324,  324,  324,  324,  380,  379,  454,  249,  454,
      253,  378,  377,   78,  254,   80,   80,   80,   80,   80,
      376,  256,  256,  256,  256,   80,  454,  375,  374,  373,
      454,   82,  372,  371,  370,  161,  259,  259,  259,  259,

      259,  369,  257,  164,  368,  364,  361,  358,   82,  258,
      357,  260,  356,  260,  161,  259,  259,  259,  259,  259,
      355,  354,  353,  352,  261,  351,  350,  349,  260,  348,
      260,  262,  262,  262,  262,  262,  314,  314,  314,  314,
      314,  347,  346,  261,  314,  314,  314,  314,  314,  345,
      344,  149,  343,  149,  324,  324,  324,  324,  324,  263,
      342,  341,  340,  339,  315,  338,  337,  306,  149,  336,
      149,  335,  315,  363,  363,  363,  363,  363,  334,  333,
      318,  318,  318,  318,  318,  363,  363,  363,  363,  363,
      363,  332,  331,  330,  329,  158,  328,  158,  156,  327,

      326,  325,  363,  363,  363,  363,  363,  363,  319,  320,
      310,  309,  158,  308,  158,  318,  318,  318,  318,  318,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      307,  306,  305,  304,  303,  366,  302,  366,  301,  300,
      299,  298,  297,  319,  296,  295,  294,  293,  367,  292,
      291,  290,  366,  367,  366,  395,  395,  395,  395,  395,
      289,  288,  365,  365,  365,  365,  365,  395,  395,  395,
      395,  395,  395,  287,  284,  283,  282,  366,  281,  366,
      280,  279,  278,  277,  395,  395,  395,  395,  395,  395,
      367,  276,  273,  272,  366,  271,  366,  415,  415,  415,

      415,  415,  270,  269,  268,  267,  266,  265,  264,  415,
      415,  415,  415,  415,  415,  451,  451,  451,  451,  243,
      156,  146,   58,  141,  224,  216,  415,  415,  415,  415,
      415,  415,   58,  215,  214,  211,  162,  210,  209,  206,
      205,  204,  203,  448,  202,  428,  428,  428,  428,  428,
      199,  198,  453,  453,  453,  453,  197,  428,  428,  428,
      428,  428,  428,  196,  195,  194,  193,  192,  191,  190,
       59,  189,  188,  257,  428,  428,  428,  428,  428,  428,
      452,  187,  186,  183,  182,  181,  180,  179,  176,  168,
      156,  147,  414,  437,  437,  437,  437,  437,   58,  134,

      133,  125,  118,  114,   95,  437,  437,  437,  437,  437,
      437,   92,   89,   66,   65,   61,   56,  454,  454,  454,
      454,  454,  437,  437,  437,  437,  437,  437,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
       57,  443,  443,  443,  443,  443,  454,  454,  454,  454,
      454,  454,  454,  443,  443,  443,  443,  443,  443,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      443,  443,  443,  443,  443,  443,  447,  447,  447,  447,
      447,  454,  454,  454,  454,  454,  454,  454,  447,  447,
      447,  447,  447,  447,  454,  454,  454,  454,  454,  454,

      454,  454,  454,  454,  454,  447,  447,  447,  447,  447,
      447,   57,  454,   57,   57,   57,   57,   57,   57,   57,
       60,  454,  454,   60,   60,   60,   60,   64,  454,   64,
      454,   64,   64,   64,   64,   64,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  155,  454,  155,  155,  155,
      155,  155,  155,  155,  169,  169,  228,  454,  454,  228,
      231,  454,  454,  231,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  252,  252,  252,  252,  321,  454,  321,
        3,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,

      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454
    } ;

static yyconst flex_int16_t yy_chk[1257] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    7,    5,    7,    9,
       12,   17,   20,   52,   19,   55,   20,   55,   20,   20,
       20,   20,   20,   35,   17,   19,   19,   21,   12,   26,

       26,   38,   21,   28,   28,   36,   37,   36,   35,  472,
       38,   21,   45,   37,   36,  145,   37,    9,   22,   37,
       22,   22,   22,   22,   22,   57,   39,   45,   39,   52,
       45,   40,  471,   22,   81,   81,   22,   39,   44,   40,
       22,   40,   44,   22,   40,   42,   48,   47,   22,  145,
       22,   42,   42,   22,   48,  470,   44,   47,   47,   22,
       47,  469,   47,   57,   94,   94,  101,  101,   75,   75,
       22,   23,  156,   23,   23,   23,   23,   23,   75,  117,
      117,  127,   78,   78,   78,   78,   78,  123,   23,   23,
       23,  467,  123,   23,  156,  131,  127,   78,   78,   78,

      199,   23,  131,  199,  137,   23,   23,   23,  133,  466,
      133,  140,   23,   59,   78,   78,   78,   59,   80,  464,
       80,   80,   80,   80,   80,  449,   59,   59,   59,   59,
      165,  165,   82,  451,   82,  446,   80,   82,   82,   82,
       82,   82,  137,   84,   84,   84,   84,   84,   80,  140,
      165,   59,  451,   80,  188,  188,   59,   87,  165,   87,
       59,  445,   87,   87,   87,   87,   87,   59,  444,  165,
       59,   84,   59,   59,   65,  230,  152,  152,   65,   85,
       85,   85,   85,   85,  132,  138,  152,   65,   65,   65,
       65,   88,   88,   88,   88,   88,  442,  230,  138,  138,

      138,  138,  132,  453,  143,  439,  132,   85,  153,  153,
      226,  139,   65,  143,  143,  143,  143,   65,  153,   88,
      438,   65,  453,  138,  139,  139,  139,  139,   65,  435,
      432,   65,  144,   65,   65,   74,   74,   74,   74,   74,
      431,  144,  144,  144,  144,  430,  429,  426,  226,  139,
       74,   74,   74,  150,  425,  150,  154,  154,  150,  150,
      150,  150,  150,   74,  310,  423,  154,   74,   74,   74,
       79,  154,   79,   79,   79,   79,   79,  237,  151,  151,
      151,  151,  151,  166,  166,  166,  166,  166,   79,  159,
      422,  159,   79,   79,  159,  159,  159,  159,  159,  237,

       79,  421,  310,  251,  250,   79,  151,  420,  234,  234,
      250,   79,  157,  157,  157,  157,  157,  160,  234,  160,
      160,  160,  160,  160,  251,  250,  316,  157,  157,  157,
      173,  173,  173,  173,  173,  160,  246,  246,  417,  160,
      157,  235,  235,  416,  157,  157,  157,  160,  316,  169,
      447,  235,  160,  163,  163,  163,  163,  163,  160,  164,
      164,  164,  164,  164,  246,  167,  167,  167,  167,  167,
      415,  169,  413,  169,  163,  170,  170,  170,  170,  169,
      167,  163,  167,  412,  411,  410,  409,  164,  447,  406,
      169,  405,  404,  167,  169,  400,  170,  167,  398,  167,

      397,  396,  393,  170,  172,  172,  172,  172,  172,  174,
      174,  174,  174,  174,  175,  175,  175,  175,  175,  229,
      225,  392,  390,  388,  174,  384,  174,  383,  229,  229,
      229,  229,  172,  225,  225,  225,  225,  174,  382,  380,
      379,  174,  175,  174,  232,  232,  232,  232,  232,  233,
      233,  233,  233,  233,  244,  244,  377,  376,  225,  241,
      241,  241,  241,  241,  233,  375,  233,  240,  240,  240,
      240,  240,  373,  321,  244,  372,  371,  233,  369,  321,
      368,  233,  244,  233,  238,  238,  238,  238,  238,  364,
      361,  359,  394,  244,  321,  240,  238,  238,  238,  238,

      238,  238,  357,  356,  242,  242,  242,  242,  242,  238,
      355,  354,  353,  238,  238,  238,  238,  238,  238,  242,
      351,  242,  247,  247,  247,  247,  247,  322,  350,  252,
      394,  238,  242,  322,  348,  347,  242,  247,  242,  247,
      249,  249,  249,  249,  249,  255,  346,  345,  322,  344,
      247,  252,  394,  252,  247,  254,  247,  254,  343,  252,
      254,  254,  254,  254,  254,  342,  341,  255,  249,  255,
      252,  340,  339,  256,  252,  256,  256,  256,  256,  256,
      337,  258,  258,  258,  258,  258,  255,  336,  335,  334,
      255,  256,  333,  328,  327,  256,  259,  259,  259,  259,

      259,  326,  258,  256,  325,  320,  312,  309,  256,  258,
      308,  259,  305,  259,  256,  261,  261,  261,  261,  261,
      304,  302,  301,  300,  259,  299,  298,  297,  259,  296,
      259,  263,  263,  263,  263,  263,  314,  314,  314,  314,
      314,  295,  294,  261,  315,  315,  315,  315,  315,  293,
      292,  314,  290,  314,  323,  323,  323,  323,  323,  263,
      288,  287,  286,  285,  314,  283,  282,  281,  314,  280,
      314,  277,  315,  317,  317,  317,  317,  317,  276,  275,
      318,  318,  318,  318,  318,  317,  317,  317,  317,  317,
      317,  274,  273,  271,  268,  318,  267,  318,  317,  266,

      265,  257,  317,  317,  317,  317,  317,  317,  318,  243,
      227,  224,  318,  223,  318,  319,  319,  319,  319,  319,
      324,  324,  324,  324,  324,  367,  367,  367,  367,  367,
      222,  220,  219,  218,  217,  324,  216,  324,  215,  214,
      213,  212,  211,  319,  210,  209,  208,  207,  324,  206,
      205,  203,  324,  367,  324,  363,  363,  363,  363,  363,
      202,  201,  365,  365,  365,  365,  365,  363,  363,  363,
      363,  363,  363,  200,  198,  196,  195,  365,  194,  365,
      193,  192,  191,  190,  363,  363,  363,  363,  363,  363,
      365,  189,  187,  186,  365,  185,  365,  395,  395,  395,

      395,  395,  184,  183,  182,  181,  180,  179,  178,  395,
      395,  395,  395,  395,  395,  448,  448,  448,  448,  162,
      155,  146,  142,  141,  134,  130,  395,  395,  395,  395,
      395,  395,  414,  129,  128,  126,  448,  125,  124,  122,
      121,  120,  119,  448,  118,  414,  414,  414,  414,  414,
      116,  114,  452,  452,  452,  452,  113,  414,  414,  414,
      414,  414,  414,  112,  111,  110,  109,  108,  107,  106,
      414,  105,  104,  452,  414,  414,  414,  414,  414,  414,
      452,  103,  102,  100,   99,   98,   97,   96,   90,   83,
       76,   73,  414,  428,  428,  428,  428,  428,   64,   50,

       49,   46,   43,   41,   34,  428,  428,  428,  428,  428,
      428,   27,   24,   16,   13,   11,    8,    3,    0,    0,
        0,    0,  428,  428,  428,  428,  428,  428,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      428,  437,  437,  437,  437,  437,    0,    0,    0,    0,
        0,    0,    0,  437,  437,  437,  437,  437,  437,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      437,  437,  437,  437,  437,  437,  443,  443,  443,  443,
      443,    0,    0,    0,    0,    0,    0,    0,  443,  443,
      443,  443,  443,  443,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,  443,  443,  443,  443,  443,
      443,  455,    0,  455,  455,  455,  455,  455,  455,  455,
      456,    0,    0,  456,  456,  456,  456,  457,    0,  457,
        0,  457,  457,  457,  457,  457,  458,  458,  458,  458,
      458,  458,  458,  458,  458,  459,    0,  459,  459,  459,
      459,  459,  459,  459,  460,  460,  461,    0,    0,  461,
      462,    0,    0,  462,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  465,  465,  465,  465,  468,    0,  468,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,

      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "java_scanner.l"
#line 2 "java_scanner.l"
#include<bits/stdc++.h>
#include<iostream>
#include "parser.tab.h"
int yylex();

using namespace std;
#line 904 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 227 "java_scanner.l"


#line 1125 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 455 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1181 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 229 "java_scanner.l"
;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 230 "java_scanner.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 233 "java_scanner.l"
{return ABSTRACT;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 234 "java_scanner.l"
{return ASSERT;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 235 "java_scanner.l"
{return BOOLEAN;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 236 "java_scanner.l"
{return BREAK;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 237 "java_scanner.l"
{return BYTE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 238 "java_scanner.l"
{return CASE;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 239 "java_scanner.l"
{return CATCH;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 240 "java_scanner.l"
{return CHAR;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 241 "java_scanner.l"
{return CLASS;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 242 "java_scanner.l"
{return CONST;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 243 "java_scanner.l"
{return CONTINUE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 244 "java_scanner.l"
{return DEFAULT;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 245 "java_scanner.l"
{return DO;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 246 "java_scanner.l"
{return DOUBLE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 247 "java_scanner.l"
{return ELSE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 248 "java_scanner.l"
{return ENUM;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 249 "java_scanner.l"
{return EXTENDS;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 250 "java_scanner.l"
{return FINAL;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 251 "java_scanner.l"
{return FINALLY;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 252 "java_scanner.l"
{return FLOAT;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 253 "java_scanner.l"
{return FOR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 254 "java_scanner.l"
{return IF;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 255 "java_scanner.l"
{return GOTO;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 256 "java_scanner.l"
{return IMPLEMENTS;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 257 "java_scanner.l"
{return IMPORT;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 258 "java_scanner.l"
{return INSTANCEOF;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 259 "java_scanner.l"
{return INT;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 260 "java_scanner.l"
{return INTERFACE;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 261 "java_scanner.l"
{return LONG;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 262 "java_scanner.l"
{return NATIVE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 263 "java_scanner.l"
{return NEW;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 264 "java_scanner.l"
{return PACKAGE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 265 "java_scanner.l"
{return PRIVATE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 266 "java_scanner.l"
{return PROTECTED;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 267 "java_scanner.l"
{return PUBLIC;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 268 "java_scanner.l"
{return RETURN;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 269 "java_scanner.l"
{return SHORT;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 270 "java_scanner.l"
{return STATIC;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 271 "java_scanner.l"
{return STRICTFP;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 272 "java_scanner.l"
{return SUPER;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 273 "java_scanner.l"
{return SWITCH;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 274 "java_scanner.l"
{return SYNCHRONIZED;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 275 "java_scanner.l"
{return THIS;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 276 "java_scanner.l"
{return THROW;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 277 "java_scanner.l"
{return THROWS;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 278 "java_scanner.l"
{return TRANSIENT;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 279 "java_scanner.l"
{return TRY;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 280 "java_scanner.l"
{return VOID;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 281 "java_scanner.l"
{return VOLATILE;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 282 "java_scanner.l"
{return WHILE;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 285 "java_scanner.l"
{return ET;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 286 "java_scanner.l"
{return GT;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 287 "java_scanner.l"
{return LT;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 288 "java_scanner.l"
{return NT;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 289 "java_scanner.l"
{return TLD;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 290 "java_scanner.l"
{return QM;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 291 "java_scanner.l"
{return COLON;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 292 "java_scanner.l"
{return AR;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 293 "java_scanner.l"
{return EQEQ;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 294 "java_scanner.l"
{return GREQ;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 295 "java_scanner.l"
{return LEQ;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 296 "java_scanner.l"
{return NEQ;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 297 "java_scanner.l"
{return INCR;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 298 "java_scanner.l"
{return DECR;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 299 "java_scanner.l"
{return OR;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 300 "java_scanner.l"
{return AND;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 301 "java_scanner.l"
{return ADD;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 302 "java_scanner.l"
{return SBTR;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 303 "java_scanner.l"
{return MULT;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 304 "java_scanner.l"
{return DIV;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 305 "java_scanner.l"
{return BOR;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 306 "java_scanner.l"
{return BAND;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 307 "java_scanner.l"
{return POW;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 308 "java_scanner.l"
{return MOD;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 309 "java_scanner.l"
{return GRGR;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 310 "java_scanner.l"
{return LTLT;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 311 "java_scanner.l"
{return GRGRGR;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 312 "java_scanner.l"
{return PLEQ;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 313 "java_scanner.l"
{return SBEQ;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 314 "java_scanner.l"
{return MULEQ;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 315 "java_scanner.l"
{return ANDEQ;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 316 "java_scanner.l"
{return OREQ;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 317 "java_scanner.l"
{return POWEQ;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 318 "java_scanner.l"
{return DIVEQ;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 319 "java_scanner.l"
{return MODEQ;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 320 "java_scanner.l"
{return DGRGR;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 321 "java_scanner.l"
{return DLRLR;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 322 "java_scanner.l"
{return TGRGRGR;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 325 "java_scanner.l"
{return LCB;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 326 "java_scanner.l"
{return RCB;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 327 "java_scanner.l"
{return LSQB;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 328 "java_scanner.l"
{return RSQB;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 329 "java_scanner.l"
{return LSMB;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 330 "java_scanner.l"
{return RSMB;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 331 "java_scanner.l"
{return CMA;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 332 "java_scanner.l"
{return DCLN;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 333 "java_scanner.l"
{return ATR;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 334 "java_scanner.l"
{return TDT;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 335 "java_scanner.l"
{return FST;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 336 "java_scanner.l"
{return SCLN;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 339 "java_scanner.l"
{return DST;}
	YY_BREAK
case 104:
/* rule 104 can match eol */
YY_RULE_SETUP
#line 342 "java_scanner.l"
{return COMMENT;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 343 "java_scanner.l"
{return LITERAL;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 344 "java_scanner.l"
{return IDENTIFIER;}
	YY_BREAK
case 107:
/* rule 107 can match eol */
YY_RULE_SETUP
#line 345 "java_scanner.l"
{return ERROR;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 347 "java_scanner.l"
ECHO;
	YY_BREAK
#line 1725 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 455 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 455 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 454);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 347 "java_scanner.l"



