
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 10
#define YY_END_OF_BUFFER 11
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[385] =
    {   0,
        0,    0,   11,    9,    1,    2,    1,    5,    9,    8,
        5,    5,    9,    4,    5,    5,    5,    4,    5,    7,
        7,    5,    5,    5,    5,    5,    8,    5,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    4,    5,    1,    5,    0,    7,
        0,    8,    0,    0,    0,    7,    0,    6,    7,    7,
        0,    0,    0,    0,    0,    7,    7,    0,    0,    4,
        5,    5,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    3,    8,    8,    8,    8,    8,    8,    8,
        8,    3,    8,    8,    8,    8,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    7,    7,    0,    0,    0,    0,    0,    6,    6,
        7,    7,    0,    7,    7,    0,    0,    0,    7,    0,
        7,    0,    7,    7,    7,    0,    0,    7,    7,    5,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    3,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        3,    8,    8,    8,    0,    0,    0,    0,    0,    0,

        0,    0,    7,    0,    0,    6,    6,    6,    7,    0,
        0,    7,    0,    7,    7,    0,    7,    7,    0,    0,
        0,    7,    7,    0,    0,    7,    0,    0,    7,    7,
        0,    7,    0,    8,    8,    8,    8,    3,    3,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    3,    8,    7,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    7,
        8,    8,    0,    0,    0,    0,    7,    0,    6,    6,
        7,    0,    0,    0,    0,    0,    7,    0,    8,    8,
        8,    8,    8,    8,    8,    3,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        3,    8,    8,    0,    0,    0,    0,    6,    0,    7,
        7,    0,    0,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    0,
        6,    0,    0,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    0,    6,    0,    0,    8,    8,    8,
        8,    8,    8,    0,    0,    0,    8,    8,    8,    0,
        0,    0,    8,    0,    0,    0,    8,    0,    0,    0,
        7,    0,    7,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   22,   22,   22,   22,   23,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   37,   38,   37,   38,   39,   37,   37,   40,   41,
       37,   37,   38,   37,   37,   37,   37,   42,   37,   37,
       43,   44,   45,   46,   47,    1,   48,   49,   50,   51,

       52,   53,   54,   55,   56,   37,   57,   58,   59,   60,
       61,   62,   37,   63,   64,   65,   66,   67,   68,   69,
       70,   71,   72,   73,   74,   75,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[76] =
    {   0,
        1,    1,    2,    2,    1,    1,    3,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    5,    1,    6,    6,
        6,    6,    6,    1,    1,    1,    1,    1,    1,    1,
        6,    6,    6,    6,    6,    6,    3,    3,    7,    3,
        8,    3,    1,    1,    1,    1,    8,    6,    6,    6,
        6,    6,    6,    3,    3,    3,    3,    7,    3,    3,
        3,    8,    3,    3,    3,    9,    3,    3,    3,    3,
        3,    1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[403] =
    {   0,
        0,    0, 1005, 1198,   74, 1198,   75,  977,   74,    0,
      976,   72,  958, 1198,  974,   68,   69,   67,   80,  102,
      155,  976,   65,  972,   73, 1198,    0,  963,   45,   41,
       55,   53,   48,   72,  928,   76,  926,   79,   84,  934,
       87,   83,  924,  929, 1198,   85,  157, 1198,  120, 1198,
      208,    0,  973,  269,  965,  317,  166,  937,  164,  354,
      202,  120,  219,  957,  225,  261, 1198,  244,  273, 1198,
      942,  135,  904,  898,  899,  907,  893,  101,  909,  908,
      895,  900,  886,  887,  877,  877,  883,  880,  878,  875,
      872,    0,  864,  103,  865,  859,  855,  864,  871,   87,

      871,  848,  850,  125,  848,  853,  841,  140,  237,  124,
      844,  187,  280,  306,  199,  833,  888,  295,  323,  182,
      830,    0, 1198,  340,  360,  207,  274,  354,  850,  168,
      394, 1198,  376,  401, 1198,  843,  435,  441,  431,  365,
      464,    0,  432,  482,    0,  446,  412,  487,  505,  865,
      826,  827,  820,  821,  816,  815,  815,  801,  799,  186,
      814,  811,  807,  799,  805,  792,  806,  804,  790,  143,
      785,  797,  794,  775,  771,  771,  760,  754,  760,  751,
      751,  747,  755,  758,  744,  747,  732,  728,  727,  733,
        0,  733,  735,  723,  524,  226,  736,    0,  529,  232,

        0,  534,  539,  306,  406, 1198,  334,  574,    0,  544,
      557,  581,  714,  592, 1198,  472,  622, 1198,  632,  364,
      363,  618, 1198,  667,  479,  674,  728,  680,  695, 1198,
      714,    0,  730,  713,  712,  722,  716,    0,    0,  717,
      706,  703,  711,  694,  701,  687,  693,  686,  678,  689,
      677,  691,  675,    0,  663,    0,  680,  677,  672,  667,
      659,  654,  656,  661,  647,  658,  652,  638,  641,    0,
      639,  646,  253,    0,  648,    0,  735,  743,  408,  772,
      779,  814,  636,  620,  623,  562,  819,  613,  629,  609,
      624,  611,  610,  614,  612,  604,  601,  584,  588,  594,

      594,  584,  572,  586,  583,  570,  579,  556,  565,  556,
      552,  558,  557,  555,    0,  554,    0,  854,  531,  861,
     1198,  824,  540,  537,  514,  506,  506,  506,  499,  495,
      492,  488,  483,  481,  467,  478,  455,  462,  455,  433,
      896,  478,  447,  432,  443,  421,  428,  426,  420,  382,
      383,  382,  386,  944,  393,  371,  374,  338,  341,  339,
      315,  309,  290,  992,  294,  291,  282,  288,  260, 1040,
      274,  267,  254, 1075,  204,  206,  205,  305,  914,  188,
      197,  951,  265, 1198, 1128, 1135, 1144, 1153, 1162, 1167,
     1168, 1172, 1181,  203, 1186,  191,  189, 1189,  175,  150,

      109,   77
    } ;

static yyconst flex_int16_t yy_def[403] =
    {   0,
      384,    1,  384,  384,  384,  384,  384,  384,  385,  386,
      384,  384,  387,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  386,  384,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  384,  384,  384,  384,  385,  384,
      384,  386,  384,  384,  384,  384,  388,  389,  384,  384,
      384,  384,  384,  390,  384,   21,  384,  384,  384,  384,
      384,  384,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,

      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  385,  385,  385,  385,  391,  384,  384,  384,  384,
      392,   56,  384,  384,  384,  388,  388,  393,  389,  389,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  394,  395,   60,   66,  384,  384,  384,   66,  384,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  385,  385,   51,  396,  384,  384,

      397,  384,  384,  388,  388,  384,  389,  389,  131,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  398,
      394,  395,  384,  384,  222,  384,  384,  384,  384,  384,
      384,  149,  384,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  385,  399,  384,  400,  384,  384,  389,  389,
      384,  384,  384,  398,  398,  384,  384,  384,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,

      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,   51,  401,  384,  402,  280,  384,  384,
      384,  384,  384,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  385,
      280,  384,  384,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  385,  389,  384,  384,  386,  386,  386,
      386,  386,  386,  354,  384,  384,  386,  386,  386,  364,
      384,  384,  386,  364,  384,  384,  386,  385,  384,  384,
      384,  384,  384,    0,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,

      384,  384
    } ;

static yyconst flex_uint16_t yy_nxt[1274] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   14,   15,   16,   14,   17,   18,   19,   20,   21,
       21,   21,   21,   22,   14,   23,   24,   25,   26,   14,
       10,   10,   27,   10,   10,   10,   10,   27,   27,   27,
       10,   10,   14,    4,   14,   28,   10,   29,   30,   31,
       32,   33,   34,   35,   10,   36,   10,   37,   27,   38,
       27,   39,   40,   41,   42,   10,   43,   44,   10,   27,
       10,   45,   46,   45,   26,   47,   47,   47,   47,   50,
       48,   48,   53,   55,   48,   56,   56,   56,   56,   56,
       71,   48,   57,   73,   48,   48,   48,   58,   48,   48,

       72,   75,   78,   76,   82,   84,   48,   85,   74,   79,
       77,   48,   80,   83,   49,   81,   86,   51,   59,   87,
       60,   60,   60,   60,   61,   50,   96,   88,   92,   89,
       97,   99,   90,   62,   93,   94,   63,  108,  139,  139,
       50,  103,  177,   64,   98,  109,  100,  178,   65,  101,
       62,  104,  105,   63,  106,  317,  107,   48,   47,   50,
       47,   48,  150,   51,  156,  157,  171,  172,  127,  127,
       64,   59,  182,   66,   66,   66,   66,   66,  128,  192,
      315,  193,  131,  131,  131,  131,  131,  183,   67,   68,
       67,   50,   50,   50,  276,  187,  274,  132,  133,  132,

      250,   69,  188,  251,   50,   67,   68,   67,  220,  127,
      127,  207,   50,  112,  132,  133,  132,  112,   59,  128,
       61,   61,   61,   61,   61,  200,  113,  113,  113,  114,
       51,   50,  140,  208,  140,  135,   63,  141,  141,  141,
      141,  141,  197,  144,  144,  144,  144,   61,  138,  242,
      243,  115,  382,   63,  135,   92,  112,  147,   50,  147,
      112,  380,  148,  148,  148,  148,  148,  112,  379,   51,
      112,   65,  112,  116,  117,  275,  127,  127,  117,  145,
      145,  145,  145,  145,  189,   50,  128,  118,  118,  118,
      119,  149,  149,  149,  149,  149,  314,  121,  195,  195,

      195,  195,  190,  135,   50,  377,  191,  146,  127,  127,
       50,   50,  120,  199,  199,  199,  199,  117,  128,   69,
      376,  117,  135,   51,  196,  196,  196,  196,  117,  375,
      373,  117,   50,  117,  121,  122,  122,  122,  122,  122,
      239,  117,  117,  117,  117,  238,  372,  371,   51,   51,
      123,  124,  123,  202,  239,  202,  205,  205,  203,  203,
      203,  203,  203,  125,  369,  238,  128,  123,  124,  123,
       59,  206,  134,  134,  134,  134,   61,  279,  122,  122,
      122,  122,  122,  141,  141,  141,  141,  141,   63,  211,
      191,  211,  135,  136,  212,  212,  212,  212,  212,  208,

      137,  368,  367,  224,  224,   63,  125,  366,  127,  127,
      285,  135,  209,  209,  209,  209,  209,   59,  128,   61,
       61,   61,   61,   61,  224,  224,  365,  132,  133,  132,
      148,  148,  148,  148,  148,   63,  130,  254,   50,  135,
      210,  363,  362,  254,  132,  133,  132,  138,  221,  214,
      214,  279,   63,  134,  134,  134,  134,   61,  135,   61,
       61,   61,   61,   61,  145,  145,  145,  145,  145,  215,
      223,  361,  224,  208,  136,  360,  314,  216,  225,  359,
      358,  137,  217,  217,  217,  217,  217,  138,  215,  223,
      214,  214,  146,  224,   92,  384,   92,  218,  354,  218,

      226,  226,  226,  226,  357,  229,  229,  229,  229,  229,
      219,  356,  353,  352,  218,  351,  218,  384,  216,  384,
      230,  227,  230,  232,  232,  232,  232,  232,  228,   50,
      350,  349,  238,  231,   92,  348,  384,  230,   50,  230,
      384,  347,  196,  196,  196,  196,  346,  117,  117,  117,
      117,  233,  203,  203,  203,  203,  203,  277,  277,  277,
      277,  277,  209,  209,  209,  209,  209,   51,  254,  191,
       92,  345,  123,   92,  123,  212,  212,  212,  212,  212,
      287,  287,  287,  287,  287,  278,  344,  343,  342,  123,
      210,  123,  280,  280,  280,  280,  280,  200,  340,  281,

      281,  281,  281,  281,  280,  280,  280,  280,  280,  280,
      214,  214,  339,  338,  132,  239,  132,  130,  337,   92,
      336,  280,  280,  280,  280,  280,  280,  282,  191,  239,
      215,  132,  239,  132,  221,  335,  334,  333,  216,  208,
      217,  217,  217,  217,  217,  254,  332,  331,  239,  215,
      217,  217,  217,  217,  217,  218,  223,  218,  224,  330,
      224,  329,  328,  384,  225,  238,  285,  327,  219,  285,
      326,  325,  218,   92,  218,  223,  324,  323,  219,  224,
      286,  224,  286,  319,  384,  287,  287,  287,  287,  287,
       59,  316,   61,   61,   61,   61,   61,  254,  226,  226,

      226,  226,   61,  313,  312,  311,  310,  309,   63,  254,
      308,  307,  135,  229,  229,  229,  229,  229,  191,  227,
      138,  306,  305,  304,  303,   63,  228,  302,  230,  301,
      230,  135,  229,  229,  229,  229,  229,  300,  299,  298,
      297,  231,  254,  296,  270,  230,  295,  230,  232,  232,
      232,  232,  232,  277,  277,  277,  277,  277,  294,  293,
      231,  277,  277,  277,  277,  277,  292,  254,  123,  254,
      123,  239,  238,  291,  290,  289,  233,  288,  283,  273,
      272,  278,  271,  191,  270,  123,  269,  123,  268,  278,
      318,  318,  318,  318,  318,  238,  267,  281,  281,  281,

      281,  281,  318,  318,  318,  318,  318,  318,  266,  265,
      264,  263,  132,  262,  132,  130,  261,  260,  259,  318,
      318,  318,  318,  318,  318,  282,  258,  257,  256,  132,
      255,  132,  281,  281,  281,  281,  281,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  254,  253,  252,
      238,  249,  321,  248,  321,  247,  246,  239,  239,  245,
      282,  244,  241,  191,  240,  322,  239,  238,  237,  321,
      322,  321,  341,  341,  341,  341,  341,  236,  235,  320,
      320,  320,  320,  320,  341,  341,  341,  341,  341,  341,
      234,   48,  213,  130,  321,  121,  321,   50,  116,  194,

      186,  341,  341,  341,  341,  341,  341,  322,  185,  184,
      181,  321,  180,  321,  355,  355,  355,  355,  355,  179,
      176,  175,   92,  174,  173,  170,  355,  355,  355,  355,
      355,  355,  381,  381,  381,  381,  169,   92,  168,  167,
      166,  165,  164,  355,  355,  355,  355,  355,  355,   50,
      163,  162,  161,  136,  160,  159,  158,  155,  154,  153,
      379,  152,  364,  364,  364,  364,  364,  151,   48,  383,
      383,  383,  383,  142,  364,  364,  364,  364,  364,  364,
      130,   70,   50,  111,  110,  102,   95,   51,   91,   48,
      227,  364,  364,  364,  364,  364,  364,  382,   48,   70,

       48,   54,   48,   48,  384,  384,  384,  384,  384,  354,
      370,  370,  370,  370,  370,  384,  384,  384,  384,  384,
      384,  384,  370,  370,  370,  370,  370,  370,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  370,
      370,  370,  370,  370,  370,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,   49,  374,  374,
      374,  374,  374,  384,  384,  384,  384,  384,  384,  384,
      374,  374,  374,  374,  374,  374,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  374,  374,  374,
      374,  374,  374,  378,  378,  378,  378,  378,  384,  384,

      384,  384,  384,  384,  384,  378,  378,  378,  378,  378,
      378,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  378,  378,  378,  378,  378,  378,   49,  384,
       49,   49,   49,   49,   49,   49,   49,   52,  384,  384,
       52,   52,   52,   52,   53,  384,   53,  384,   53,   53,
       53,   53,   53,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  129,  384,  129,  129,  129,  129,  129,  129,
      129,  143,  143,  198,  384,  384,  198,  201,  384,  384,
      201,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      222,  222,  222,  222,  284,  384,  284,    3,  384,  384,

      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384
    } ;

static yyconst flex_int16_t yy_chk[1274] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    7,    5,    7,    9,
       12,   16,  402,   18,   17,   18,   18,   18,   18,   18,
       23,   23,   19,   29,   16,   17,   17,   19,   12,   25,

       25,   30,   31,   30,   32,   33,   19,   33,   29,   31,
       30,   46,   31,   32,  401,   31,   33,    9,   20,   34,
       20,   20,   20,   20,   20,   49,   38,   34,   36,   34,
       38,   39,   34,   20,   36,   36,   20,   42,   62,   62,
       20,   41,  100,   20,   38,   42,   39,  100,   20,   39,
       20,   41,   41,   20,   41,  400,   41,   46,   47,   20,
       47,   72,   72,   49,   78,   78,   94,   94,   57,   57,
       20,   21,  104,   21,   21,   21,   21,   21,   57,  110,
      399,  110,   59,   59,   59,   59,   59,  104,   21,   21,
       21,  120,  112,   21,  397,  108,  396,   59,   59,   59,

      170,   21,  108,  170,  115,   21,   21,   21,  394,  126,
      126,  130,   21,   51,   59,   59,   59,   51,   61,  126,
       61,   61,   61,   61,   61,  120,   51,   51,   51,   51,
      112,  196,   63,  130,   63,  381,   61,   63,   63,   63,
       63,   63,  115,   65,   65,   65,   65,   65,   61,  160,
      160,   51,  380,   61,  381,  377,   51,   68,  273,   68,
       51,  376,   68,   68,   68,   68,   68,   51,  375,  196,
       51,   65,   51,   51,   54,  200,  127,  127,   54,   66,
       66,   66,   66,   66,  109,  113,  127,   54,   54,   54,
       54,   69,   69,   69,   69,   69,  273,  200,  113,  113,

      113,  113,  109,  383,  118,  373,  109,   66,  204,  204,
      378,  114,   54,  118,  118,  118,  118,   54,  204,   69,
      372,   54,  383,  113,  114,  114,  114,  114,   54,  371,
      369,   54,  119,   54,   54,   56,   56,   56,   56,   56,
      368,  119,  119,  119,  119,  367,  366,  365,  378,  114,
       56,   56,   56,  124,  363,  124,  128,  128,  124,  124,
      124,  124,  124,   56,  362,  361,  128,   56,   56,   56,
       60,  128,   60,   60,   60,   60,   60,  207,  125,  125,
      125,  125,  125,  140,  140,  140,  140,  140,   60,  133,
      360,  133,   60,   60,  133,  133,  133,  133,  133,  207,

       60,  359,  358,  221,  220,   60,  125,  357,  205,  205,
      220,   60,  131,  131,  131,  131,  131,  134,  205,  134,
      134,  134,  134,  134,  221,  220,  356,  131,  131,  131,
      147,  147,  147,  147,  147,  134,  355,  353,  340,  134,
      131,  352,  351,  350,  131,  131,  131,  134,  143,  139,
      139,  279,  134,  137,  137,  137,  137,  137,  134,  138,
      138,  138,  138,  138,  146,  146,  146,  146,  146,  139,
      143,  349,  143,  279,  137,  348,  340,  139,  143,  347,
      346,  137,  141,  141,  141,  141,  141,  138,  139,  143,
      216,  216,  146,  143,  345,  225,  344,  141,  340,  141,

      144,  144,  144,  144,  343,  148,  148,  148,  148,  148,
      141,  342,  339,  338,  141,  337,  141,  225,  216,  225,
      148,  144,  148,  149,  149,  149,  149,  149,  144,  195,
      336,  335,  334,  148,  333,  332,  225,  148,  199,  148,
      225,  331,  195,  195,  195,  195,  330,  199,  199,  199,
      199,  149,  202,  202,  202,  202,  202,  203,  203,  203,
      203,  203,  210,  210,  210,  210,  210,  195,  329,  328,
      327,  326,  203,  325,  203,  211,  211,  211,  211,  211,
      286,  286,  286,  286,  286,  203,  324,  323,  319,  203,
      210,  203,  208,  208,  208,  208,  208,  316,  314,  212,

      212,  212,  212,  212,  208,  208,  208,  208,  208,  208,
      214,  214,  313,  312,  212,  311,  212,  208,  310,  309,
      308,  208,  208,  208,  208,  208,  208,  212,  307,  306,
      214,  212,  305,  212,  222,  304,  303,  302,  214,  208,
      217,  217,  217,  217,  217,  301,  300,  299,  298,  214,
      219,  219,  219,  219,  219,  217,  222,  217,  222,  297,
      284,  296,  295,  285,  222,  294,  284,  293,  217,  285,
      292,  291,  217,  290,  217,  222,  289,  288,  219,  222,
      224,  284,  224,  283,  285,  224,  224,  224,  224,  224,
      226,  275,  226,  226,  226,  226,  226,  272,  228,  228,

      228,  228,  228,  271,  269,  268,  267,  266,  226,  265,
      264,  263,  226,  229,  229,  229,  229,  229,  262,  228,
      226,  261,  260,  259,  258,  226,  228,  257,  229,  255,
      229,  226,  231,  231,  231,  231,  231,  253,  252,  251,
      250,  229,  249,  248,  247,  229,  246,  229,  233,  233,
      233,  233,  233,  277,  277,  277,  277,  277,  245,  244,
      231,  278,  278,  278,  278,  278,  243,  242,  277,  241,
      277,  240,  237,  236,  235,  234,  233,  227,  213,  197,
      194,  277,  193,  192,  190,  277,  189,  277,  188,  278,
      280,  280,  280,  280,  280,  187,  186,  281,  281,  281,

      281,  281,  280,  280,  280,  280,  280,  280,  185,  184,
      183,  182,  281,  181,  281,  280,  180,  179,  178,  280,
      280,  280,  280,  280,  280,  281,  177,  176,  175,  281,
      174,  281,  282,  282,  282,  282,  282,  287,  287,  287,
      287,  287,  322,  322,  322,  322,  322,  173,  172,  171,
      169,  168,  287,  167,  287,  166,  165,  164,  163,  162,
      282,  161,  159,  158,  157,  287,  156,  155,  154,  287,
      322,  287,  318,  318,  318,  318,  318,  153,  152,  320,
      320,  320,  320,  320,  318,  318,  318,  318,  318,  318,
      151,  150,  136,  129,  320,  121,  320,  117,  116,  111,

      107,  318,  318,  318,  318,  318,  318,  320,  106,  105,
      103,  320,  102,  320,  341,  341,  341,  341,  341,  101,
       99,   98,   97,   96,   95,   93,  341,  341,  341,  341,
      341,  341,  379,  379,  379,  379,   91,   90,   89,   88,
       87,   86,   85,  341,  341,  341,  341,  341,  341,  354,
       84,   83,   82,  379,   81,   80,   79,   77,   76,   75,
      379,   74,  354,  354,  354,  354,  354,   73,   71,  382,
      382,  382,  382,   64,  354,  354,  354,  354,  354,  354,
       58,   55,   53,   44,   43,   40,   37,  354,   35,   28,
      382,  354,  354,  354,  354,  354,  354,  382,   24,   22,

       15,   13,   11,    8,    3,    0,    0,    0,    0,  354,
      364,  364,  364,  364,  364,    0,    0,    0,    0,    0,
        0,    0,  364,  364,  364,  364,  364,  364,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  364,
      364,  364,  364,  364,  364,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  364,  370,  370,
      370,  370,  370,    0,    0,    0,    0,    0,    0,    0,
      370,  370,  370,  370,  370,  370,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  370,  370,  370,
      370,  370,  370,  374,  374,  374,  374,  374,    0,    0,

        0,    0,    0,    0,    0,  374,  374,  374,  374,  374,
      374,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  374,  374,  374,  374,  374,  374,  385,    0,
      385,  385,  385,  385,  385,  385,  385,  386,    0,    0,
      386,  386,  386,  386,  387,    0,  387,    0,  387,  387,
      387,  387,  387,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  389,    0,  389,  389,  389,  389,  389,  389,
      389,  390,  390,  391,    0,    0,  391,  392,    0,    0,
      392,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      395,  395,  395,  395,  398,    0,  398,  384,  384,  384,

      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "java_scanner.l"
#line 2 "java_scanner.l"
#include "java_scanner.h"
int lineno=1;
#line 882 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 117 "java_scanner.l"


#line 1103 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 385 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1198 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 119 "java_scanner.l"
;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 120 "java_scanner.l"
{lineno++;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 121 "java_scanner.l"
{return KEYWORD;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 122 "java_scanner.l"
{return SEPARATOR;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 123 "java_scanner.l"
{return OPERATOR;}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 124 "java_scanner.l"
{return COMMENT;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 125 "java_scanner.l"
{return LITERAL;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 126 "java_scanner.l"
{return IDENTIFIER;}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 127 "java_scanner.l"
{return ERROR;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 129 "java_scanner.l"
ECHO;
	YY_BREAK
#line 1213 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 385 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 385 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 384);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 129 "java_scanner.l"



int yywrap(void)
{
	return 1;
}
